# Generated by Django 4.2.7 on 2024-01-11 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='unidades',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidades',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
