# Generated by Django 3.2.22 on 2024-01-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisional', '0002_auto_20240111_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
